# Generated by Django 3.1.13 on 2021-12-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloan',
            options={'verbose_name': 'User Loan', 'verbose_name_plural': 'User Loans'},
        ),
        migrations.AlterModelTable(
            name='userloan',
            table='user_loan',
        ),
    ]
